#!/bin/bash

ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

docker run -v $ABSOLUTE_PATH/../output:/home/fenics/lvk/output \
           -v $ABSOLUTE_PATH/../src:/home/fenics/lvk/src \
           -p 8888:8888 \
           --rm -it --name lvk lvk fenics-notebook
