#!/bin/bash

ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

docker run -v $ABSOLUTE_PATH/../output:/home/fenics/lvk/output \
           -v $ABSOLUTE_PATH/../src:/home/fenics/lvk/src \
           -p 8080:8080 \
           --rm -it --name lvk-report \
           lvk "report-server 0.0.0.0 8080"
 
